FROM {{ image_spec("base-tools") }}
MAINTAINER {{ maintainer }}

RUN apt-get update \
    && apt-get install -y -t jessie-backports nginx \
    && usermod -a -G microservices www-data

COPY nginx.conf /etc/nginx/nginx.conf
COPY nginx_proxy-headers.conf /etc/nginx/common/proxy-headers.conf
COPY nginx_ssl.conf /etc/nginx/common/ssl.conf
