FROM {{ image_spec("base-tools") }}
MAINTAINER {{ maintainer }}

RUN apt-get update \
    && apt-get install -y nginx \
    && usermod -a -G microservices www-data

COPY nginx.conf /etc/nginx/nginx.conf
